posts:          /actualites/:year-:month-:day-:slug/
categories:     /actualites/:slug/
authors:        /actualites/auteurs/:slug/
projects:       /projets/:year-:slug/
types:          /projets/:slug/
