posts:          /news/:year-:month-:day-:slug/
categories:     /news/:slug/
tags:           /news/tags/:slug/
authors:        /news/authors/:slug/
projects:       /projects/:year-:slug/
types:          /projects/:slug/
casestudies:    /case-studies/:slug/
publications:   /publications/:slug/
pages:          /:sections[1:]/:filename/
