posts:          /news/:year-:month-:day-:slug/
categories:     /news/:slug/
tags:           /news/tags/:slug/
authors:        /news/:slug/

persons:        /team/:slug/

projects:       /projects/:year-:slug/
types:          /projects/:slug/

casestudies:    /case-studies/:slug/

publications:   /publications/:slug/
concerned:      /publications/:slug/

