[build]
  command = "yarn build"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.158.0"
  GO_VERSION = "1.24.2"

[context.production.environment]
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.branch-deploy.environment]
  HUGO_ENV = "production"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
