collections_config:
  products:
    path: content/products
    output: true
    url: /products/[slug]/
    _enabled_editors:
      - content
      - visual
  pages:
    path: content
    output: true
    url: /[slug]/
    _enabled_editors:
      - content
      - visual

_array_structures:
  blocks:
    values:
      - label: Title Block
        icon: ballot
        value:
          type: title
          heading:
            title:
            text:
      - label: Paragraph Block
        icon: ballot
        value:
          type: paragraph
          heading:
            title:
            text:
