---
label: test
hide_body: true
fields:
- name: title
  type: text
  config:
    required: true
  label: Title
- name: blocks
  type: blocks
  label: Blocks
  template_types: []
  config:
    min: 1
    max: 10
